version: '3.9'

services:
  postgres:
    image: postgres
    container_name: give-me-postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "give-me-db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d give-me-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis
    container_name: give-me-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
